all:
	(cd ../docbook/developer; ./mkhookdocs)
	(cd user; make)
	(cd admin; make)
	(cd developer; make)
	(cd api; make)
	(cd faq; make)
	(cd db; make)

clean:
	(cd user; make clean)
	(cd admin; make clean)
	(cd developer; make clean)
	(cd api; make clean)
	(cd faq; make clean)
	(cd db; make clean)

